theme: jekyll-theme-minimal
title: GeoBeer Analytics
description: A collection of analytics about GeoBeer events, including the tools to produce them. Hopefully useful also to other meetup and event organisers.
logo: assets/logo-geobeer.png
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - about.md
