theme: jekyll-theme-minimal
title: GeoBeer Analytics
description: A one-pager about analytics of [GeoBeer](http://www.geobeer.ch) events. Hopefully useful also to other tech meetup organisers.
logo: assets/logo-geobeer.png
show_downloads: "true"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - about.md
