theme: jekyll-theme-minimal
title: GeoBeer Analytics
description: A one-pager about analytics of GeoBeer events. Hopefully useful also to other meetup and event organisers.
logo: assets/logo-geobeer.png
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - about.md
